
const fetchCountryCodes = async (req, res) => {
  try {
    const countryCodes = [
      {'code': '+1', 'country': 'United States/Canada', 'flag': 'US'},
      {'code': '+1', 'country': 'Caribbean', 'flag': 'TT'},
      {'code': '+7', 'country': 'Russia/Kazakhstan', 'flag': 'RU'},
      {'code': '+20', 'country': 'Egypt', 'flag': 'EG'},
      {'code': '+27', 'country': 'South Africa', 'flag': 'ZA'},
      {'code': '+30', 'country': 'Greece', 'flag': 'GR'},
      {'code': '+31', 'country': 'Netherlands', 'flag': 'NL'},
      {'code': '+32', 'country': 'Belgium', 'flag': 'BE'},
      {'code': '+33', 'country': 'France', 'flag': 'FR'},
      {'code': '+34', 'country': 'Spain', 'flag': 'ES'},
      {'code': '+36', 'country': 'Hungary', 'flag': 'HU'},
      {'code': '+39', 'country': 'Italy', 'flag': 'IT'},
      {'code': '+40', 'country': 'Romania', 'flag': 'RO'},
      {'code': '+41', 'country': 'Switzerland', 'flag': 'CH'},
      {'code': '+43', 'country': 'Austria', 'flag': 'AT'},
      {'code': '+44', 'country': 'United Kingdom', 'flag': 'GB'},
      {'code': '+45', 'country': 'Denmark', 'flag': 'DK'},
      {'code': '+46', 'country': 'Sweden', 'flag': 'SE'},
      {'code': '+47', 'country': 'Norway', 'flag': 'NO'},
      {'code': '+48', 'country': 'Poland', 'flag': 'PL'},
      {'code': '+49', 'country': 'Germany', 'flag': 'DE'},
      {'code': '+51', 'country': 'Peru', 'flag': 'PE'},
      {'code': '+52', 'country': 'Mexico', 'flag': 'MX'},
      {'code': '+53', 'country': 'Cuba', 'flag': 'CU'},
      {'code': '+54', 'country': 'Argentina', 'flag': 'AR'},
      {'code': '+55', 'country': 'Brazil', 'flag': 'BR'},
      {'code': '+56', 'country': 'Chile', 'flag': 'CL'},
      {'code': '+57', 'country': 'Colombia', 'flag': 'CO'},
      {'code': '+58', 'country': 'Venezuela', 'flag': 'VE'},
      {'code': '+60', 'country': 'Malaysia', 'flag': 'MY'},
      {'code': '+61', 'country': 'Australia', 'flag': 'AU'},
      {'code': '+62', 'country': 'Indonesia', 'flag': 'ID'},
      {'code': '+63', 'country': 'Philippines', 'flag': 'PH'},
      {'code': '+64', 'country': 'New Zealand', 'flag': 'NZ'},
      {'code': '+65', 'country': 'Singapore', 'flag': 'SG'},
      {'code': '+66', 'country': 'Thailand', 'flag': 'TH'},
      {'code': '+81', 'country': 'Japan', 'flag': 'JP'},
      {'code': '+82', 'country': 'South Korea', 'flag': 'KR'},
      {'code': '+84', 'country': 'Vietnam', 'flag': 'VN'},
      {'code': '+86', 'country': 'China', 'flag': 'CN'},
      {'code': '+90', 'country': 'Turkey', 'flag': 'TR'},
      {'code': '+91', 'country': 'India', 'flag': 'IN'},
      {'code': '+92', 'country': 'Pakistan', 'flag': 'PK'},
      {'code': '+93', 'country': 'Afghanistan', 'flag': 'AF'},
      {'code': '+94', 'country': 'Sri Lanka', 'flag': 'LK'},
      {'code': '+95', 'country': 'Myanmar', 'flag': 'MM'},
      {'code': '+98', 'country': 'Iran', 'flag': 'IR'},
      {'code': '+212', 'country': 'Morocco', 'flag': 'MA'},
      {'code': '+213', 'country': 'Algeria', 'flag': 'DZ'},
      {'code': '+216', 'country': 'Tunisia', 'flag': 'TN'},
      {'code': '+218', 'country': 'Libya', 'flag': 'LY'},
      {'code': '+220', 'country': 'Gambia', 'flag': 'GM'},
      {'code': '+221', 'country': 'Senegal', 'flag': 'SN'},
      {'code': '+222', 'country': 'Mauritania', 'flag': 'MR'},
      {'code': '+223', 'country': 'Mali', 'flag': 'ML'},
      {'code': '+224', 'country': 'Guinea', 'flag': 'GN'},
      {'code': '+225', 'country': 'Ivory Coast', 'flag': 'CI'},
      {'code': '+226', 'country': 'Burkina Faso', 'flag': 'BF'},
      {'code': '+227', 'country': 'Niger', 'flag': 'NE'},
      {'code': '+228', 'country': 'Togo', 'flag': 'TG'},
      {'code': '+229', 'country': 'Benin', 'flag': 'BJ'},
      {'code': '+230', 'country': 'Mauritius', 'flag': 'MU'},
      {'code': '+231', 'country': 'Liberia', 'flag': 'LR'},
      {'code': '+232', 'country': 'Sierra Leone', 'flag': 'SL'},
      {'code': '+233', 'country': 'Ghana', 'flag': 'GH'},
      {'code': '+234', 'country': 'Nigeria', 'flag': 'NG'},
      {'code': '+235', 'country': 'Chad', 'flag': 'TD'},
      {'code': '+236', 'country': 'Central African Republic', 'flag': 'CF'},
      {'code': '+237', 'country': 'Cameroon', 'flag': 'CM'},
      {'code': '+238', 'country': 'Cape Verde', 'flag': 'CV'},
      {'code': '+239', 'country': 'Sao Tome and Principe', 'flag': 'ST'},
      {'code': '+240', 'country': 'Equatorial Guinea', 'flag': 'GQ'},
      {'code': '+241', 'country': 'Gabon', 'flag': 'GA'},
      {'code': '+242', 'country': 'Republic of the Congo', 'flag': 'CG'},
      {'code': '+243', 'country': 'Democratic Republic of the Congo', 'flag': 'CD'},
      {'code': '+244', 'country': 'Angola', 'flag': 'AO'},
      {'code': '+245', 'country': 'Guinea-Bissau', 'flag': 'GW'},
      {'code': '+246', 'country': 'British Indian Ocean Territory', 'flag': 'IO'},
      {'code': '+248', 'country': 'Seychelles', 'flag': 'SC'},
      {'code': '+249', 'country': 'Sudan', 'flag': 'SD'},
      {'code': '+250', 'country': 'Rwanda', 'flag': 'RW'},
      {'code': '+251', 'country': 'Ethiopia', 'flag': 'ET'},
      {'code': '+252', 'country': 'Somalia', 'flag': 'SO'},
      {'code': '+253', 'country': 'Djibouti', 'flag': 'DJ'},
      {'code': '+254', 'country': 'Kenya', 'flag': 'KE'},
      {'code': '+255', 'country': 'Tanzania', 'flag': 'TZ'},
      {'code': '+256', 'country': 'Uganda', 'flag': 'UG'},
      {'code': '+257', 'country': 'Burundi', 'flag': 'BI'},
      {'code': '+258', 'country': 'Mozambique', 'flag': 'MZ'},
      {'code': '+260', 'country': 'Zambia', 'flag': 'ZM'},
      {'code': '+261', 'country': 'Madagascar', 'flag': 'MG'},
      {'code': '+262', 'country': 'Réunion/Mayotte', 'flag': 'RE'},
      {'code': '+263', 'country': 'Zimbabwe', 'flag': 'ZW'},
      {'code': '+264', 'country': 'Namibia', 'flag': 'NA'},
      {'code': '+265', 'country': 'Malawi', 'flag': 'MW'},
      {'code': '+266', 'country': 'Lesotho', 'flag': 'LS'},
      {'code': '+267', 'country': 'Botswana', 'flag': 'BW'},
      {'code': '+268', 'country': 'Eswatini', 'flag': 'SZ'},
      {'code': '+269', 'country': 'Comoros', 'flag': 'KM'},
      {'code': '+290', 'country': 'Saint Helena', 'flag': 'SH'},
      {'code': '+291', 'country': 'Eritrea', 'flag': 'ER'},
      {'code': '+297', 'country': 'Aruba', 'flag': 'AW'},
      {'code': '+298', 'country': 'Faroe Islands', 'flag': 'FO'},
      {'code': '+299', 'country': 'Greenland', 'flag': 'GL'},
      {'code': '+350', 'country': 'Gibraltar', 'flag': 'GI'},
      {'code': '+351', 'country': 'Portugal', 'flag': 'PT'},
      {'code': '+352', 'country': 'Luxembourg', 'flag': 'LU'},
      {'code': '+353', 'country': 'Ireland', 'flag': 'IE'},
      {'code': '+354', 'country': 'Iceland', 'flag': 'IS'},
      {'code': '+355', 'country': 'Albania', 'flag': 'AL'},
      {'code': '+356', 'country': 'Malta', 'flag': 'MT'},
      {'code': '+357', 'country': 'Cyprus', 'flag': 'CY'},
      {'code': '+358', 'country': 'Finland', 'flag': 'FI'},
      {'code': '+359', 'country': 'Bulgaria', 'flag': 'BG'},
      {'code': '+370', 'country': 'Lithuania', 'flag': 'LT'},
      {'code': '+371', 'country': 'Latvia', 'flag': 'LV'},
      {'code': '+372', 'country': 'Estonia', 'flag': 'EE'},
      {'code': '+373', 'country': 'Moldova', 'flag': 'MD'},
      {'code': '+374', 'country': 'Armenia', 'flag': 'AM'},
      {'code': '+375', 'country': 'Belarus', 'flag': 'BY'},
      {'code': '+376', 'country': 'Andorra', 'flag': 'AD'},
      {'code': '+377', 'country': 'Monaco', 'flag': 'MC'},
      {'code': '+378', 'country': 'San Marino', 'flag': 'SM'},
      {'code': '+379', 'country': 'Vatican City', 'flag': 'VA'},
      {'code': '+380', 'country': 'Ukraine', 'flag': 'UA'},
      {'code': '+381', 'country': 'Serbia', 'flag': 'RS'},
      {'code': '+382', 'country': 'Montenegro', 'flag': 'ME'},
      {'code': '+383', 'country': 'Kosovo', 'flag': 'XK'},
      {'code': '+385', 'country': 'Croatia', 'flag': 'HR'},
      {'code': '+386', 'country': 'Slovenia', 'flag': 'SI'},
      {'code': '+387', 'country': 'Bosnia and Herzegovina', 'flag': 'BA'},
      {'code': '+389', 'country': 'North Macedonia', 'flag': 'MK'},
      {'code': '+420', 'country': 'Czech Republic', 'flag': 'CZ'},
      {'code': '+421', 'country': 'Slovakia', 'flag': 'SK'},
      {'code': '+423', 'country': 'Liechtenstein', 'flag': 'LI'},
      {'code': '+500', 'country': 'Falkland Islands', 'flag': 'FK'},
      {'code': '+501', 'country': 'Belize', 'flag': 'BZ'},
      {'code': '+502', 'country': 'Guatemala', 'flag': 'GT'},
      {'code': '+503', 'country': 'El Salvador', 'flag': 'SV'},
      {'code': '+504', 'country': 'Honduras', 'flag': 'HN'},
      {'code': '+505', 'country': 'Nicaragua', 'flag': 'NI'},
      {'code': '+506', 'country': 'Costa Rica', 'flag': 'CR'},
      {'code': '+507', 'country': 'Panama', 'flag': 'PA'},
      {'code': '+508', 'country': 'Saint Pierre and Miquelon', 'flag': 'PM'},
      {'code': '+509', 'country': 'Haiti', 'flag': 'HT'},
      {'code': '+590', 'country': 'Guadeloupe', 'flag': 'GP'},
      {'code': '+591', 'country': 'Bolivia', 'flag': 'BO'},
      {'code': '+592', 'country': 'Guyana', 'flag': 'GY'},
      {'code': '+593', 'country': 'Ecuador', 'flag': 'EC'},
      {'code': '+594', 'country': 'French Guiana', 'flag': 'GF'},
      {'code': '+595', 'country': 'Paraguay', 'flag': 'PY'},
      {'code': '+596', 'country': 'Martinique', 'flag': 'MQ'},
      {'code': '+597', 'country': 'Suriname', 'flag': 'SR'},
      {'code': '+598', 'country': 'Uruguay', 'flag': 'UY'},
      {'code': '+599', 'country': 'Curaçao/Caribbean Netherlands', 'flag': 'CW'},
      {'code': '+670', 'country': 'Timor-Leste', 'flag': 'TL'},
      {'code': '+672', 'country': 'Norfolk Island', 'flag': 'NF'},
      {'code': '+673', 'country': 'Brunei', 'flag': 'BN'},
      {'code': '+674', 'country': 'Nauru', 'flag': 'NR'},
      {'code': '+675', 'country': 'Papua New Guinea', 'flag': 'PG'},
      {'code': '+676', 'country': 'Tonga', 'flag': 'TO'},
      {'code': '+677', 'country': 'Solomon Islands', 'flag': 'SB'},
      {'code': '+678', 'country': 'Vanuatu', 'flag': 'VU'},
      {'code': '+679', 'country': 'Fiji', 'flag': 'FJ'},
      {'code': '+680', 'country': 'Palau', 'flag': 'PW'},
      {'code': '+681', 'country': 'Wallis and Futuna', 'flag': 'WF'},
      {'code': '+682', 'country': 'Cook Islands', 'flag': 'CK'},
      {'code': '+683', 'country': 'Niue', 'flag': 'NU'},
      {'code': '+685', 'country': 'Samoa', 'flag': 'WS'},
      {'code': '+686', 'country': 'Kiribati', 'flag': 'KI'},
      {'code': '+687', 'country': 'New Caledonia', 'flag': 'NC'},
      {'code': '+688', 'country': 'Tuvalu', 'flag': 'TV'},
      {'code': '+689', 'country': 'French Polynesia', 'flag': 'PF'},
      {'code': '+690', 'country': 'Tokelau', 'flag': 'TK'},
      {'code': '+691', 'country': 'Micronesia', 'flag': 'FM'},
      {'code': '+692', 'country': 'Marshall Islands', 'flag': 'MH'},
      {'code': '+850', 'country': 'North Korea', 'flag': 'KP'},
      {'code': '+852', 'country': 'Hong Kong', 'flag': 'HK'},
      {'code': '+853', 'country': 'Macau', 'flag': 'MO'},
      {'code': '+855', 'country': 'Cambodia', 'flag': 'KH'},
      {'code': '+856', 'country': 'Laos', 'flag': 'LA'},
      {'code': '+880', 'country': 'Bangladesh', 'flag': 'BD'},
      {'code': '+886', 'country': 'Taiwan', 'flag': 'TW'},
      {'code': '+960', 'country': 'Maldives', 'flag': 'MV'},
      {'code': '+961', 'country': 'Lebanon', 'flag': 'LB'},
      {'code': '+962', 'country': 'Jordan', 'flag': 'JO'},
      {'code': '+963', 'country': 'Syria', 'flag': 'SY'},
      {'code': '+964', 'country': 'Iraq', 'flag': 'IQ'},
      {'code': '+965', 'country': 'Kuwait', 'flag': 'KW'},
      {'code': '+966', 'country': 'Saudi Arabia', 'flag': 'SA'},
      {'code': '+967', 'country': 'Yemen', 'flag': 'YE'},
      {'code': '+968', 'country': 'Oman', 'flag': 'OM'},
      {'code': '+970', 'country': 'Palestine', 'flag': 'PS'},
      {'code': '+971', 'country': 'United Arab Emirates', 'flag': 'AE'},
      {'code': '+972', 'country': 'Israel', 'flag': 'IL'},
      {'code': '+973', 'country': 'Bahrain', 'flag': 'BH'},
      {'code': '+974', 'country': 'Qatar', 'flag': 'QA'},
      {'code': '+975', 'country': 'Bhutan', 'flag': 'BT'},
      {'code': '+976', 'country': 'Mongolia', 'flag': 'MN'},
      {'code': '+977', 'country': 'Nepal', 'flag': 'NP'},
      {'code': '+992', 'country': 'Tajikistan', 'flag': 'TJ'},
      {'code': '+993', 'country': 'Turkmenistan', 'flag': 'TM'},
      {'code': '+994', 'country': 'Azerbaijan', 'flag': 'AZ'},
      {'code': '+995', 'country': 'Georgia', 'flag': 'GE'},
      {'code': '+996', 'country': 'Kyrgyzstan', 'flag': 'KG'},
      {'code': '+998', 'country': 'Uzbekistan', 'flag': 'UZ'}
    ];

    // Sort alphabetically by country name
    const sortedCountryCodes = countryCodes.sort((a, b) => 
      a.country.localeCompare(b.country)
    );

    res.status(200).json({
      status: 200,
      message: 'Successfully fetched country codes',
      data: sortedCountryCodes
    });
    
  } catch (error) {
    console.error('Error fetching country codes:', error);
    res.status(500).json({
      status: 500,
      message: 'Internal server error'
    });
  }
};

module.exports = {
  fetchCountryCodes
};