name: Build, Push, and Deploy (versioned, compose-aware)

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  IMAGE_NAME: freelixlaos/freelix-backend         # Docker Hub repo
  DEPLOY_PATH: /opt/freelix-backend               # folder on server that already has your docker-compose.yml
  SERVICE_NAME: freelix-backend                   # compose service/container name for backend

jobs:
  build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      VERSION: ${{ steps.pkg.outputs.VERSION }}
      IMAGE_TAG: ${{ steps.pkg.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node (read package.json)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Read version from package.json
        id: pkg
        run: |
          VERSION=$(node -p "require('./package.json').version || ''")
          if [ -z "$VERSION" ]; then
            echo "VERSION=latest" >> $GITHUB_OUTPUT
            echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
            echo "IMAGE_TAG=v$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.pkg.outputs.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Server (update compose backend only)
    needs: build-and-push
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      IMAGE_TAG: ${{ needs.build-and-push.outputs.IMAGE_TAG }}
      DEPLOY_PATH: ${{ env.DEPLOY_PATH }}
      SERVICE_NAME: ${{ env.SERVICE_NAME }}

    steps:
      - name: Deploy via SSH (sudo)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 1234 }}
          timeout: 60s
          command_timeout: 20m
          script: |
            set -euo pipefail

            # Sanity
            if ! command -v docker >/dev/null 2>&1; then
              echo "docker not found on server"; exit 1
            fi
            if ! docker compose version >/dev/null 2>&1; then
              echo "docker compose v2 not found"; exit 1
            fi

            echo "Login Docker Hub..."
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Go to deploy folder with your existing compose (contains mysql + backend)
            sudo mkdir -p "${DEPLOY_PATH}"
            cd "${DEPLOY_PATH}"

            if [ ! -f docker-compose.yml ]; then
              echo "docker-compose.yml not found in ${DEPLOY_PATH} — aborting to avoid overwriting your running stack."
              exit 1
            fi

            echo "Current compose services:"
            sudo docker compose config --services

            # OPTIONAL: ensure MySQL network is up
            sudo docker network inspect backend >/dev/null 2>&1 || sudo docker network create backend

            # Update ONLY the backend image tag inside compose file
            # This looks for the line under the backend service: image: freelixlaos/freelix-backend:...
            sudo sed -i -E "s|(^[[:space:]]*image:[[:space:]]*)${IMAGE_NAME}:[[:alnum:]._-]+|\1${IMAGE_NAME}:${IMAGE_TAG}|g" docker-compose.yml

            echo "Compose diff (context around image):"
            grep -n -A2 -B2 -E "image:.*${IMAGE_NAME}" docker-compose.yml || true

            echo "Pull the new backend image..."
            sudo docker pull "${IMAGE_NAME}:${IMAGE_TAG}"

            # Wait for mysql healthy before touching backend (best-effort)
            echo "Waiting for MySQL healthy (max ~90s)..."
            ATTEMPTS=0
            until [ "$(sudo docker inspect --format='{{json .State.Health.Status}}' mysql-prod 2>/dev/null | tr -d '\"')" = "healthy" ] || [ $ATTEMPTS -ge 9 ]; do
              ATTEMPTS=$((ATTEMPTS+1))
              sleep 10
            done

            echo "Recreate only backend with the new image..."
            sudo docker compose pull ${SERVICE_NAME}
            sudo docker compose up -d ${SERVICE_NAME}

            echo "Prune dangling images..."
            sudo docker image prune -f

            echo "Status:"
            sudo docker ps --filter "name=${SERVICE_NAME}"
            sudo docker compose ps

            echo "Recent backend logs (30 lines):"
            sudo docker logs --tail=30 ${SERVICE_NAME} || true
